config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'

  post 'tasks/:id/toggle', to: 'tasks#toggle'
  resources :tasks

  get '/signup', to: 'users#new'
  get '/profile', to: 'users#profile'
  get '/profile/edit', to: 'users#edit'
  post '/user/update', to: 'users#update_from_project'
  resources :users, except: %i(new edit)

  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'

  resources :comments, only: %i(create)

  post '/list/update', to: 'lists#update_from_project'
  resources :lists

  resources :projects, only: %i(index create show)
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :description, presence: true

  belongs_to :task
  belongs_to :user
end

app/models/list.rb
class List < ApplicationRecord
  validates :title, presence: true, uniqueness: true

  belongs_to :project
  has_many :tasks
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true

  has_many :lists
  has_many :user_projects
  has_many :users, through: :user_projects
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true

  belongs_to :list
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  after_create :set_hash_name

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  has_many :comments
  has_many :user_projects
  has_many :projects, through: :user_projects

  has_secure_password

  private
  def set_hash_name
    update(name: SecureRandom.hex(10))
  end
end

app/models/user_project.rb
class UserProject < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @task = Task.find(params[:comment][:id].to_i)
    comment = Comment.new(
      description: params[:comment][:description],
      task_id: @task.id,
      user_id: current_user.id
    )
    if comment.save
      flash[:success] = 'コメントを作成しました。'
      redirect_to task_path(@task)
    else
      flash[:danger] = 'コメントは作成できませんでした。'
      redirect_to task_path(@task)
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @list = List.new
    @lists = List.all
  end

  def create
    List.create(list_params)
    redirect_to lists_path
  end

  def show
    @task = Task.new
    @list = List.find(params[:id])
  end

  def update_from_project
    list = List.find_or_create_by(title: params[:title])
    if list
      list.update(project_id: params[:id])

      flash[:success] = "リストの追加に成功しました。"
      redirect_to project_path(params[:id])
    else
      flash[:danger] = "リストの追加に失敗しました。"
      redirect_to project_path(params[:id])
    end
  end

  private

  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :redirect_signin

  def index
    @project = Project.new
    projects_ids = UserProject.where(user_id: current_user.id).pluck(:project_id)
    @projects = Project.where(id: projects_ids)
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      UserProject.create!(user_id: current_user.id, project_id: @project.id)
      flash[:success] = "プロジェクトの作成に成功しました。"
      redirect_to project_path(@project)
    else
      flash[:danger] = "プロジェクトの作成に失敗しました。"
      redirect_to projects_path
    end
  end

  def show
    @project = Project.find(params[:id])
    @not_have_user_emails = User.where.not(id: @project.user_ids).map(&:email)
  end

  private
  def project_params
    params.require(:project).permit(:title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      flash[:success] = 'ログインに成功しました。'
      redirect_to profile_path
    else
      flash[:danger] = 'メールアドレス、またはパスワードが違います。'
      redirect_to signin_path
    end
  end

  def destroy
    log_out
    redirect_to signin_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :redirect_signin
  def index
    @task = Task.new
    @tasks_not_yet = Task.where(complete: false)
    @tasks_done = Task.where(complete: true)
  end

  def create
    @list = List.find(params[:task][:id].to_i)
    task = Task.create(
      title: params[:task][:title],
      list_id: @list.id
    )

    redirect_to list_path(@list)
  end

  def show
    @task = Task.find(params[:id])
    @comment = Comment.new
  end

  def destroy
    Task.find(params[:id]).destroy
    redirect_to list_path(params[:id])
  end

  def toggle
    @task = Task.find(params[:id])
    bool = request.body.read
    merge_params(bool)
    @task.update(complete: params[:complete])
  end

  private
  def task_params
    params.require(:task).permit(:title)
  end

  def merge_params(bool)
    if bool == "false"
      params.merge!(complete: false)
    else
      params.merge!(complete: true)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def profile
    @user = User.find(current_user.id)
    render 'show'
  end

  def edit
    @user = User.find(current_user.id)
    unless @user && logged_in?
      redirect_to signin_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = '更新しました。'
      redirect_to @user
    else
      flash[:danger] = '更新に失敗しました。'
      redirect_to edit_user_path
    end
  end

  def update_from_project
    user = User.find_by_email(params[:email])
    project_id = params[:id]
    if user && project_id
      UserProject.create(user_id: user.id, project_id: project_id)
      flash[:success] = "ユーザーの更新に成功しました。"
      redirect_to project_path(project_id)
    else
      flash[:danger] = "ユーザーの更新に失敗しました。"
      redirect_to project_path(project_id)
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def logged_in?
    !current_user.nil?
  end

  private

  def redirect_signin
    redirect_to signin_path unless logged_in?
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lists/index.html.erb
<h1>リスト一覧</h1>
<div>
  <%= form_with(model: @list, local: true) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.submit "作成" %>
  <% end %>
</div>
<div>
  <% @lists.each do |list| %>
    <li><%= link_to list.title, list_path(list) %></li>
  <% end %>
</div>

app/views/lists/show.html.erb
<div>
  <h2 class="text-3xl pb-8"><%= @list.title %></h2>
  <div>
    <%= form_with(model: @task, local: true) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.hidden_field :id, :value => params[:id] %>
      <%= f.submit "作成" %>
    <% end %>
  </div>

  <div class="pt-8">
    <div data-controller="tasks">
      <% @list.tasks.each do |task| %>
        <% if task.complete == false %>
          <%= form_with(model: task) do |f| %>
            <%= f.check_box :complete, data: {
              id: task.id,
              action: "tasks#toggle"
            } %>
            <span class="text-blue-500">
              <%= link_to(task.title, task_path(task)) %>
            </span>
            <span class="text-red-500">
              <%= link_to('削除', "/tasks/#{task.id}", data: {turbo_method: :delete}) %>
            </span>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="pt-6">
      <h1>終了済み</h1>
      <div data-controller="tasks">
        <% @list.tasks.each do |task| %>
          <% if task.complete == true %>
            <%= form_with(model: task) do |f| %>
              <%= f.check_box :complete, data: {
                id: task.id,
                action: "tasks#toggle"
              } %>
              <span class="pt-5 text-blue-500">
                <%= link_to(task.title, task_path(task), class: 'pt-3') %>
              </span>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div>
  <%= form_with(model: @project, local: true) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.submit "作成" %>
  <% end %>
  <h1 class="text-xl">プロジェクト一覧</h1>
  <div>
    <ul>
      <% @projects.each do |project| %>
        <li class="pt-5 pl-3 text-blue-500">
          <%= link_to(project.title, project_path(project)) %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/projects/show.html.erb
<div>
  <h2 class="text-3xl pb-8"><%= @project.title %></h2>
  <div class="grid grid-cols-2">
    <div>
      <%= form_with url: list_update_path do |f| %>
        <%= f.text_field :title %>

        <%= f.hidden_field :id, :value => params[:id] %>
        <%= f.submit "追加" %>
      <% end %>
      <h2>タスクリスト一覧</h2>
      <ul>
        <% @project.lists.each do |list| %>
          <li class="pt-5 text-blue-500">
            <%= link_to(list.title, list_path(list)) %>
          </li>
        <% end %>
      </ul>
    </div>
    <div>
      <%= form_with url: user_update_path do |f| %>
        <%= f.select(:email, @not_have_user_emails, include_blank: true) %>

        <%= f.hidden_field :id, :value => params[:id] %>
        <%= f.submit "追加" %>
      <% end %>
      <h2>ユーザー一覧</h2>
      <ul>
        <% @project.users.each do |user| %>
          <li class="pt-5 text-blue-500">
            <%= link_to(user.name, profile_path) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div>
  <%= form_with(model: @task, local: true) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.submit "作成" %>
  <% end %>
</div>
<div>
  <h2>未着手</h2>
  <div data-controller="tasks">
    <% @tasks_not_yet.each do |task| %>
      <%= form_with(model: task) do |f| %>
        <%= f.check_box :complete, data: {
          id: task.id,
          action: "tasks#toggle"
        } %>
        <%= link_to(task.title, task_path(task)) %>
      <% end %>
    <% end %>
  </div>
</div>
<div class="pt-5">
  <h2>終了</h2>
  <div data-controller="tasks">
    <% @tasks_done.each do |task| %>
      <%= form_with(model: task) do |f| %>
        <%= f.check_box :complete, checked: true, data: {
          id: task.id,
          action: "tasks#toggle"
        } %>
        <%= link_to(task.title, task_path(task)) %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/tasks/show.html.erb
<h2 class="text-xl "><%= @task.title %></h2>
<div class="pt-5">
  <% @task.comments.each do |comment| %>
    <div class="pt-3">
      <span>user: </span>
      <span>
        <%= comment.user.name %>
    </span>
    </div>
    <div>
      <span>comment: </span>
      <span><%= comment.description %></span>
    </div>
  <% end %>
</div>

<div>
  <%= form_with(model: @comment, local: true) do |f| %>
    <%= f.text_field :description %>

    <%= f.hidden_field :id, :value => params[:id] %>
    <%= f.submit "コメント", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded" %>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>


  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Save changes", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded" %>
<% end %>

app/views/users/new.html.erb
<div>
  <%= form_with(model: @user, local: true) do |f| %>
    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "アカウント作成", class: "bg-blue-500 hover:bg-blue-400 text-white font-bold py-2 px-4 border-b-4 border-blue-700 hover:border-blue-500 rounded" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div>
  <div><%= @user.name %></div>
  <div><%= @user.email %></div>
  <% if current_user.email == @user.email %>
    <%= link_to '編集', profile_edit_path, class: "text-blue-500 background-transparent font-bold uppercase px-3 py-1 text-xs outline-none focus:outline-none mr-1 mb-1 ease-linear transition-all duration-150" %>
  <% end %>
</div>